sudo: required
services:
  - docker

before_install:
  - docker build -t stuartsmiller/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stuartsmiller/docker-react npm run test
