sudo: required
services:
  - docker

before_install:
  - docker build -t stuartsmiller/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stuartsmiller/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  regin: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-945922923484"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
